//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tombo.rc
//
#define IDS_PROPTAB_FOLDER              1
#define IDS_PROPTAB_TITLE               2
#define IDS_PROPTAB_PASSWORD            3
#define IDS_PROPERTY_PASSWORD_DESC      4
#define IDS_PROPTAB_PASS_TIMEOUT        5
#define IDS_PROPTAB_FONT                6
#define IDS_PROPTAB_DATE                7
#define IDS_PROPTAB_KEEPCARET           8
#define IDS_TIPS_NEWMEMO                9
#define IDS_TIPS_SAVE                   10
#define IDS_PROPTAB_SELECTMEMO          11
#define IDS_GREPTAB_MAIN                12
#define IDS_GREPTAB_PERSIST             13
#define IDS_PROPTAB_DEFNOTE             14
#define ID_MENU_MAIN                    101
#define ID_CMDBAR_MAIN                  101
#define IDR_MENU_MAIN                   101
#define IDC_MEMOSELECTVIEW              102
#define IDB_MEMOSELECT_IMAGES           102
#define IDC_MEMODETAILSVIEW             103
#define IDD_PASSWORD                    104
#define ID_PASSWORDTIMER                104
#define IDB_TOOLBAR                     105
#define IDC_TOOLBAR                     105
#define IDR_DUMMY                       106
#define IDC_STATUS                      106
#define IDD_ABOUTBOX                    107
#define IDC_MEMODETAILSVIEW_NF          107
#define IDI_TOMBO                       109
#define IDB_ARTICLEBOX                  110
#define IDD_PROPTAB                     111
#define IDD_FILESELECT                  112
#define IDC_TOPFOLDER                   113
#define IDC_FOLDERSEL                   114
#define IDC_FILESELECT_TREE             115
#define IDD_PROPTAB_FOLDER              116
#define IDD_PROPTAB_PASSWORD            117
#define IDC_PASS1                       118
#define IDC_PASS2                       119
#define IDD_NEWFOLDER                   120
#define IDC_NEWFOLDER_NAME              121
#define IDD_PROPTAB_PASS_TIMEOUT        122
#define IDD_PROPTAB_FONT                124
#define IDD_PROPTAB_INSDATE             125
#define IDR_ACCEL_SELECT                127
#define IDR_ACCEL_DETAIL                128
#define IDD_PROPTAB_KEEPCARET           129
#define IDD_PROPTAB_SELECTMEMO          130
#define IDD_SEARCH                      132
#define IDR_CONTEXTMENU                 133
#define IDD_SEARCHING                   134
#define IDD_GREPTAB_MAIN                135
#define IDD_GREPTAB_PERSIST             136
#define IDD_FILTERCTL                   137
#define IDD_FILTERDEF_SRC               138
#define IDD_FILTERDEF_FILTER            139
#define IDD_FILTERDEF_ADD_REGEX         140
#define IDD_FILTERDEF_ADD_LIMIT         141
#define IDD_FILTERDEF_ADD_TIMESTAMP     142
#define IDD_FILTERDEF_ADD_SORT          143
#define IDD_FILTERDEF_VIEWTYPE          144
#define IDD_PROPTAB_DEFNOTE             146
#define IDD_BOOKMARK_EDIT               147
#define IDC_PASS                        1000
#define IDC_PROP_PASSWORD_DESC          1001
#define IDC_PASS_TIMEOUT                1002
#define IDC_FONT_SELECT_NAME            1003
#define IDC_FONT_DETAILS_NAME           1004
#define IDC_FONT_SELECT_SIZE            1005
#define IDC_FONT_DETAILS_SIZE           1006
#define IDC_FONT_SELECT_USEDEFAULT      1007
#define IDC_FONT_DETAILS_USEDEFAULT     1008
#define IDC_PROP_DATEFORMAT1            1008
#define IDC_PROP_DATEFORMAT2            1009
#define IDC_PROP_SETPASS                1011
#define IDC_PROP_KEEPCARET              1012
#define IDC_PROP_SINGLECLICK            1013
#define IDC_PROP_AUTOLOAD               1014
#define IDC_PROP_TABSTOP                1015
#define IDC_PROP_SWITCHTITLE            1016
#define IDC_KEEPTITLE                   1017
#define IDC_SEARCH_STRING               1019
#define IDC_SEARCH_CASESENSITIVE        1020
#define IDC_SEARCH_ENCRYPTMEMO          1021
#define IDC_COPYRIGHT                   1022
#define IDC_FILENAMEONLY                1023
#define IDC_DATEFORMAT_DESC             1025
#define IDC_VERSIONINFO                 1026
#define IDC_SEARCH_DIRECTION_UP         1027
#define IDC_SEARCH_DIRECTION_DOWN       1028
#define IDC_SEARCHMSG                   1029
#define IDC_GREPTAB_MAIN_STARTDIR       1030
#define IDC_GREPTAB_MAIN_SEARCHSTRING   1031
#define IDC_GREPTAB_MAIN_CASESENSITIVE  1032
#define IDC_GREPTAB_MAIN_ENCRYPTNOTE    1033
#define IDC_GREPTAB_MAIN_FILENAME       1034
#define IDC_GREPTAB_PERSIST_NAME        1035
#define IDC_PROPTAB_PERSIST_SELECTPERSIST 1036
#define IDC_PROP_READONLY               1037
#define IDC_FILTERCTL_LIST              1038
#define IDC_FILTERCTL_UP                1039
#define IDC_FILTERCTL_DOWN              1040
#define IDC_FILTERCTL_NEW               1041
#define IDC_FILTERCTL_KEEP              1042
#define IDC_FILTERDEF_SRC_PATH          1043
#define IDC_FILTERCTL_DELETE            1043
#define IDC_FILTERDEF_FILTER_LIST       1044
#define IDC_FILTERCTL_RENAME            1044
#define IDC_FILTERDEF_FILTER_UP         1045
#define IDC_FILTERDEF_FILTER_DOWN       1046
#define IDC_FILTERDEF_FILTER_REGEX      1047
#define IDC_FILTERDEF_FILTER_LIMIT      1048
#define IDC_FILTERDEF_REGEX_SEARCHSTR   1048
#define IDC_FILTERDEF_FILTER_TIMESTAMP  1049
#define IDC_FILTERDEF_REGEX_CASESENSITIVE 1049
#define IDC_FILTERDEF_FILTER_SORT       1050
#define IDC_FILTERDEF_REGEX_CRYPTMEMO   1050
#define IDC_FILTERDEF_REGEX_FILENAME    1051
#define IDC_FILTERDEF_FILTER_DELETE     1051
#define IDC_FILTERDEF_REGEX_NEGATE      1052
#define IDC_FILTERDEF_LIMIT_NUMLIMIT    1054
#define IDC_FILTERDEF_TS_DELTADAY       1055
#define IDC_FILTERDEF_TS_OLDER          1056
#define IDC_FILTERDEF_TS_NEWER          1057
#define IDC_FILTERDEF_SORT_TYPE         1058
#define IDC_FONT_SELECT_CLEARTYPE       1059
#define IDC_FONT_DETAILS_CLEARTYPE      1060
#define IDC_FILTERDEF_VIEW_TYPE         1060
#define IDC_PROPTAB_DEFNOTE_PATH        1061
#define IDC_PROPTAB_DEFNOTE_SETCURRENT  1062
#define IDC_PROPTAB_DEFNOTE_SETBLANK    1063
#define IDC_BMEDIT_LIST                 1063
#define IDC_BMEDIT_DELETE               1064
#define IDC_BMEDIT_UP                   1065
#define IDC_BMEDIT_DOWN                 1066
#define IDM_EXIT                        40001
#define IDM_NEWMEMO                     40002
#define IDM_RETURNLIST                  40003
#define IDM_DETAILSVIEW_CUT             40004
#define IDM_CUT                         40004
#define IDM_DETAILSVIEW_COPY            40005
#define IDM_COPY                        40005
#define IDM_DETAILSVIEW_PASTE           40006
#define IDM_PASTE                       40006
#define IDM_ENCRYPT                     40007
#define IDM_DECRYPT                     40008
#define IDM_ABOUT                       40009
#define IDM_DELETEITEM                  40010
#define IDM_PROPERTY                    40011
#define IDM_ACTIONBUTTON                40012
#define IDM_NEWFOLDER                   40013
#define IDM_FORGETPASS                  40014
#define IDM_SAVE                        40015
#define IDM_INSDATE1                    40016
#define IDM_INSDATE2                    40017
#define IDM_SELALL                      40018
#define IDM_DETAILS_HSCROLL             40020
#define IDM_TOGGLEPANE                  40022
#define IDM_SEARCH                      40023
#define IDM_SEARCH_NEXT                 40024
#define IDM_SEARCH_PREV                 40025
#define IDM_RENAME                      40026
#define IDM_TOGGLEREADONLY              40028
#define IDM_UNDO                        40029
#define IDM_SHOWSTATUSBAR               40030
#define IDM_GREP                        40031
#define IDM_TOPMOST                     40032
#define IDM_VFOLDER_DEF                 40034
#define IDM_TRACELINK                   40035
#define IDM_BOOKMARK_ADD                40037
#define IDM_BOOKMARK_CONFIG             40038

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1067
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
