//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tombo.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_HELLOWINCE                  3
#define IDI_TOMBO                       101
#define IDC_MEMODETAILSVIEW             101
#define IDC_MEMOSELECTVIEW              102
#define IDD_ABOUTBOX                    103
#define IDB_MEMOSELECT_IMAGES           104
#define ID_PASSWORDTIMER                104
#define IDD_PASSWORD                    105
#define ID_CMDBAR_MAIN                  105
#define IDD_PROPTAB_FOLDER              106
#define ID_CMDBAR_DETAILS               106
#define IDD_FILESELECT                  107
#define IDC_MEMODETAILSVIEW_NF          107
#define IDB_ARTICLEBOX                  108
#define IDC_STATUS                      108
#define IDD_PROPTAB_PASSWORD            109
#define IDC_TOOLBAR                     109
#define IDD_NEWFOLDER                   110
#define IDC_CMDBAND                     110
#define IDD_PROPTAB_PASS_TIMEOUT        111
#define ID_MENUBAND                     111
#define ID_BUTTONBAND                   112
#define IDB_TOOLBAR                     115
#define IDB_TOOLBAR_DETAILS             116
#define IDD_PROPTAB_FONT                117
#define IDD_PROPTAB_INSDATE             118
#define IDR_ACCEL_SELECT                120
#define IDR_ACCEL_DETAIL                121
#define IDD_PROPTAB_KEEPCARET           122
#define IDD_SEARCH                      126
#define IDI_REBAR                       127
#define IDB_REBAR                       128
#define IDD_SEARCHING                   129
#define IDD_GREPTAB_MAIN                130
#define IDD_GREPTAB_PERSIST             131
#define IDD_FILTERCTL                   132
#define IDR_CONTEXTMENU                 133
#define IDD_FILTERDEF_SRC               138
#define IDD_FILTERDEF_FILTER            139
#define IDD_FILTERDEF_ADD_REGEX         140
#define IDD_FILTERDEF_ADD_LIMIT         141
#define IDD_FILTERDEF_ADD_TIMESTAMP     142
#define IDD_FILTERDEF_ADD_SORT          143
#define IDM_MAIN_MENUITEM1              401
#define IDM_MAIN_MENUITEM2              402
#define IDS_MAIN_MENUITEM1              410
#define IDS_MAIN_MENUITEM2              412
#define IDM_MAIN_MENU                   450
#define IDR_MENU_MAIN                   450
#define IDM_DETAILS_MENU                460
#define IDR_MENU_DETAILS                460
#define IDC_PASS                        1001
#define IDC_TOPFOLDER                   1002
#define IDC_FOLDERSEL                   1003
#define IDC_FILESELECT_TREE             1004
#define IDC_PASS1                       1005
#define IDC_PASS2                       1006
#define IDC_PROP_PASSWORD_DESC          1007
#define IDC_NEWFOLDER_NAME              1008
#define IDC_PASS_TIMEOUT                1010
#define IDC_FONT_SELECT_NAME            1011
#define IDC_FONT_DETAILS_NAME           1012
#define IDC_FONT_SELECT_SIZE            1013
#define IDC_FONT_DETAILS_SIZE           1014
#define IDC_FONT_SELECT_USEDEFAULT      1015
#define IDC_FONT_DETAILS_USEDEFAULT     1016
#define IDC_PROP_DATEFORMAT1            1017
#define IDC_PROP_DATEFORMAT2            1018
#define IDC_PROP_SETPASS                1018
#define IDC_PROP_KEEPCARET              1019
#define IDC_PROP_TABSTOP                1020
#define IDC_KEEPTITLE                   1021
#define IDC_SEARCH_STRING               1022
#define IDC_SEARCH_CASESENSITIVE        1023
#define IDC_SEARCH_ENCRYPTMEMO          1024
#define IDC_EDIT1                       1025
#define IDC_COPYRIGHT                   1025
#define IDC_DATEFORMAT_DESC             1025
#define IDC_FILENAMEONLY                1026
#define IDC_VERSIONINFO                 1028
#define IDC_SEARCH_DIRECTION_UP         1029
#define IDC_SEARCH_DIRECTION_DOWN       1030
#define IDC_SEARCHMSG                   1031
#define IDC_GREPTAB_MAIN_SEARCHSTRING   1032
#define IDC_GREPTAB_MAIN_CASESENSITIVE  1033
#define IDC_GREPTAB_MAIN_ENCRYPTNOTE    1034
#define IDC_GREPTAB_MAIN_FILENAME       1035
#define IDC_GREPTAB_MAIN_STARTDIR       1036
#define IDC_PROP_READONLY               1037
#define IDC_FILTERCTL_LIST              1041
#define IDC_FILTERCTL_KEEP              1042
#define IDC_FILTERCTL_UP                1043
#define IDC_FILTERDEF_SRC_PATH          1043
#define IDC_FILTERCTL_DOWN              1044
#define IDC_FILTERDEF_FILTER_LIST       1044
#define IDC_FILTERCTL_NEW               1045
#define IDC_FILTERDEF_FILTER_UP         1045
#define IDC_FILTERDEF_FILTER_DOWN       1046
#define IDC_FILTERCTL_DELETE            1046
#define IDC_FILTERDEF_FILTER_REGEX      1047
#define IDC_FILTERCTL_RENAME            1047
#define IDC_FILTERDEF_REGEX_SEARCHSTR   1048
#define IDC_FILTERDEF_FILTER_LIMIT      1048
#define IDC_FILTERDEF_REGEX_CASESENSITIVE 1049
#define IDC_FILTERDEF_FILTER_TIMESTAMP  1049
#define IDC_FILTERDEF_REGEX_CRYPTMEMO   1050
#define IDC_FILTERDEF_FILTER_SORT       1050
#define IDC_FILTERDEF_REGEX_FILENAME    1051
#define IDC_FILTERDEF_FILTER_DELETE     1051
#define IDC_FILTERDEF_REGEX_NEGATE      1052
#define IDC_FILTERDEF_LIMIT_NUMLIMIT    1054
#define IDC_FILTERDEF_TS_DELTADAY       1055
#define IDC_FILTERDEF_TS_OLDER          1056
#define IDC_FILTERDEF_TS_NEWER          1057
#define IDC_FILTERDEF_SORT_TYPE         1058
#define IDC_FONT_SELECT_CLEARTYPE       1059
#define IDC_FONT_DETAILS_CLEARTYPE      1060
#define IDM_ACTIONBUTTON                30001
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_EXIT                        40003
#define IDS_MENUITEM40005               40006
#define IDM_EDIT_MEMO                   40007
#define IDM_DETAILSVIEW_CUT             40008
#define IDM_DETAILSVIEW_COPY            40009
#define IDM_DETAILSVIEW_PASTE           40010
#define IDS_MENUITEM40011               40012
#define IDM_MENUITEM3                   40013
#define IDS_MENUITEM40014               40015
#define IDS_MENUITEM40017               40018
#define IDM_NEWMEMO                     40019
#define IDS_MENUITEM40020               40021
#define IDM_RETURNLIST                  40022
#define IDM_ABOUT                       40023
#define IDM_ENCRYPT                     40024
#define IDM_DECRYPT                     40025
#define IDS_MENUITEM40027               40028
#define IDM_MENU_ENCRYPT                40029
#define IDS_PROPTAB_FOLDER              40029
#define IDM_DELETEITEM                  40030
#define IDS_PROPTAB_TITLE               40030
#define IDM_PROPERTY                    40031
#define IDS_PROPTAB_PASSWORD            40031
#define IDS_PROPERTY_PASSWORD_DESC      40032
#define IDM_NEW                         40032
#define IDS_MENUITEM40033               40034
#define IDM_NEWFOLDER                   40035
#define IDS_PROPTAB_PASS_TIMEOUT        40035
#define IDM_FORGETPASS                  40036
#define IDS_MENUITEM40037               40038
#define IDS_MENUITEM40039               40040
#define IDM_COPY                        40041
#define IDS_MENUITEM40041               40041
#define IDS_PROPTAB_FONT                40041
#define IDM_PASTE                       40042
#define IDS_PROPTAB_DATE                40042
#define IDM_CUT                         40043
#define IDS_PROPTAB_KEEPCARET           40043
#define IDS_GREPTAB_MAIN                40044
#define IDM_SAVE                        40045
#define IDS_GREPTAB_PERSIST             40045
#define IDM_INSDATE1                    40046
#define IDM_INSDATE2                    40047
#define IDM_SELALL                      40048
#define IDM_DETAILS_HSCROLL             40049
#define IDM_TOGGLEPANE                  40050
#define IDM_SEARCH                      40051
#define IDM_SEARCH_NEXT                 40052
#define IDM_SEARCH_PREV                 40053
#define IDM_RENAME                      40054
#define IDM_UNDO                        40055
#define IDM_TOGGLEREADONLY              40056
#define IDM_SHOWSTATUSBAR               40057
#define IDM_GREP                        40058
#define IDM_VFOLDER_DEF                 40059
#define IDM_TRACELINK                   40060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40061
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
