open(SRC, "TomboMsg_en.txt") || die;
open(OUT, ">DefaultMsg.cpp") || die;

print OUT <<HEADER ;
// This file is generated by GenBuildInResource.pl. Do not edit this file.
static LPCTSTR defaultMsg[] = {
HEADER

while(<SRC>) {
	chop;
	print OUT "	TEXT(\"$_\"),\n";
}

print OUT <<FOOTER ;
};
FOOTER

close(OUT);
close(SRC);
