
open(SRC, "MsgIdList.txt") || die;
open(INCL, ">MsgDef.h") || die;

print INCL <<INCLHEAD ;
// This file is generated by GenMsgIncl.pl. DO NOT EDIT THIS FILE.

INCLHEAD

#######################

$i = 1;
while(<SRC>) {
	chop;
	/^MSG_(.*)$/;
	print INCL "#define MSG_ID_$1 $i\n";
	print INCL "#define $_ (g_mMsgRes.GetMsg(MSG_ID_$1))\n";
	print INCL "\n";
	$i++;
}

$i--;

print INCL <<INCLFOOT ;

#define NUM_MESSAGES $i
INCLFOOT

close(INCL);
close(SRC);

# ====================================================

open(SRC, "TomboMsg_en.txt") || die;
open(OUT, ">DefaultMsg.cpp") || die;

print OUT <<HEADER ;
// This file is generated by GenBuildInResource.pl. Do not edit this file.
static LPCTSTR defaultMsg[] = {
HEADER

while(<SRC>) {
	chop;
	print OUT "	TEXT(\"$_\"),\n";
}

print OUT <<FOOTER ;
};
FOOTER

close(OUT);
close(SRC);
