
open(SRC, "MsgIdList.txt") || die;
open(INCL, ">MsgDef.h") || die;

print INCL <<INCLHEAD ;
// This file is generated by GenMsgIncl.pl. DO NOT EDIT THIS FILE.

INCLHEAD

#######################

$i = 1;
while(<SRC>) {
	chop;
	print INCL "#define $_ (g_mMsgRes.GetMsg($i))\n";
	$i++;
}

$i--;

print INCL <<INCLFOOT ;

#define NUM_MESSAGES $i
INCLFOOT

close(INCL);
close(SRC);
