//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TomboE.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_HELLOWINCE                  3
#define IDI_TOMBO                       101
#define IDC_MEMODETAILSVIEW             101
#define IDC_MEMOSELECTVIEW              102
#define IDD_ABOUTBOX                    103
#define IDB_MEMOSELECT_IMAGES           104
#define ID_PASSWORDTIMER                104
#define IDD_PASSWORD                    105
#define ID_CMDBAR_MAIN                  105
#define IDD_PROPTAB_FOLDER              106
#define ID_CMDBAR_DETAILS               106
#define IDD_FILESELECT                  107
#define IDC_MEMODETAILSVIEW_NF          107
#define IDB_ARTICLEBOX                  108
#define IDD_PROPTAB_PASSWORD            109
#define IDD_NEWFOLDER                   110
#define IDD_PROPTAB_PASS_TIMEOUT        111
#define IDB_TOOLBAR                     115
#define IDB_TOOLBAR_DETAILS             116
#define IDD_PROPTAB_FONT                117
#define IDD_PROPTAB_INSDATE             118
#define IDR_ACCEL_SELECT                119
#define IDR_ACCEL_DETAIL                120
#define IDD_PROPTAB_KEEPCARET           121
#define IDD_SEARCH                      122
#define IDM_MAIN_MENUITEM1              401
#define IDM_MAIN_MENUITEM2              402
#define IDS_MAIN_MENUITEM1              410
#define IDS_MAIN_MENUITEM2              412
#define IDM_MAIN_MENU                   450
#define IDR_MENU_MAIN                   450
#define IDM_DETAILS_MENU                460
#define IDR_MENU_DETAILS                460
#define IDC_PASS                        1001
#define IDC_TOPFOLDER                   1002
#define IDC_FOLDERSEL                   1003
#define IDC_FILESELECT_TREE             1004
#define IDC_PASS1                       1005
#define IDC_PASS2                       1006
#define IDC_PROP_PASSWORD_DESC          1007
#define IDC_NEWFOLDER_NAME              1008
#define IDC_PASS_TIMEOUT                1010
#define IDC_FONT_SELECT_NAME            1011
#define IDC_FONT_DETAILS_NAME           1012
#define IDC_FONT_SELECT_SIZE            1013
#define IDC_FONT_DETAILS_SIZE           1014
#define IDC_FONT_SELECT_USEDEFAULT      1015
#define IDC_FONT_DETAILS_USEDEFAULT     1016
#define IDC_PROP_DATEFORMAT1            1017
#define IDC_PROP_DATEFORMAT2            1018
#define IDC_PROP_SETPASS                1018
#define IDC_PROP_KEEPCARET              1019
#define IDC_PROP_TABSTOP                1020
#define IDC_KEEPTITLE                   1021
#define IDC_SEARCH_STRING               1022
#define IDC_SEARCH_CASESENSITIVE        1023
#define IDC_SEARCH_ENCRYPTMEMO          1024
#define IDC_COPYRIGHT                   1027
#define IDC_FILENAMEONLY                1028
#define IDC_DATEFORMAT_DESC             1030
#define IDC_VERSIONINFO                 1031
#define IDM_ACTIONBUTTON                30001
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_EXIT                        40003
#define IDS_MENUITEM40005               40006
#define IDM_EDIT_MEMO                   40007
#define IDM_DETAILSVIEW_CUT             40008
#define IDM_DETAILSVIEW_COPY            40009
#define IDM_DETAILSVIEW_PASTE           40010
#define IDS_MENUITEM40011               40012
#define IDM_MENUITEM3                   40013
#define IDS_MENUITEM40014               40015
#define IDS_MENUITEM40017               40018
#define IDM_NEWMEMO                     40019
#define IDS_MENUITEM40020               40021
#define IDM_RETURNLIST                  40022
#define IDM_ABOUT                       40023
#define IDM_ENCRYPT                     40024
#define IDM_DECRYPT                     40025
#define IDS_MENUITEM40027               40028
#define IDM_MENU_ENCRYPT                40029
#define IDS_PROPTAB_FOLDER              40029
#define IDM_DELETEITEM                  40030
#define IDS_PROPTAB_TITLE               40030
#define IDM_PROPERTY                    40031
#define IDS_PROPTAB_PASSWORD            40031
#define IDS_PROPERTY_PASSWORD_DESC      40032
#define IDM_NEW                         40032
#define IDS_MENUITEM40033               40034
#define IDM_NEWFOLDER                   40035
#define IDS_PROPTAB_PASS_TIMEOUT        40035
#define IDM_FORGETPASS                  40036
#define IDS_MENUITEM40037               40038
#define IDS_MENUITEM40039               40040
#define IDM_COPY                        40041
#define IDS_MENUITEM40041               40041
#define IDS_PROPTAB_FONT                40041
#define IDM_PASTE                       40042
#define IDS_PROPTAB_DATE                40042
#define IDM_CUT                         40043
#define IDS_PROPTAB_KEEPCARET           40043
#define IDM_SAVE                        40045
#define IDM_INSDATE1                    40046
#define IDM_INSDATE2                    40047
#define IDM_SELALL                      40048
#define IDM_DETAILS_HSCROLL             40049
#define IDM_SEARCH                      40050
#define IDM_SEARCH_NEXT                 40051
#define IDM_SEARCH_PREV                 40052
#define IDM_RENAME                      40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40054
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
