//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tombo.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_HELLOWINCE                  3
#define IDI_TOMBO                       101
#define IDC_MEMODETAILSVIEW             101
#define IDC_MEMOSELECTVIEW              102
#define IDD_ABOUTBOX                    103
#define IDB_MEMOSELECT_IMAGES           104
#define ID_PASSWORDTIMER                104
#define IDD_PASSWORD                    105
#define IDC_MEMODETAILSVIEW_NF          105
#define IDD_PROPTAB_FOLDER              106
#define IDC_DETAILSVIEWDLG              106
#define IDD_FILESELECT                  107
#define IDM_TRACELINK                   107
#define IDB_ARTICLEBOX                  108
#define IDM_ASSOC                       108
#define IDD_PROPTAB_PASSWORD            109
#define IDM_EXTAPP1                     109
#define IDD_NEWFOLDER                   110
#define IDM_EXTAPP2                     110
#define IDD_PROPTAB_PASS_TIMEOUT        111
#define IDC_TOMBOEDIT                   111
#define IDD_PROPTAB_FONT                112
#define IDT_SELSCROLL                   112
#define IDB_TOOLBAR                     114
#define IDR_MENUBAR1                    115
#define IDR_POPUP                       115
#define IDD_PROPTAB_INSDATE             116
#define IDR_ACCEL_SELECT                117
#define IDR_ACCEL_DETAIL                118
#define IDD_PROPTAB_KEEPCARET           119
#define IDD_PROPTAB_APPBUTTON           120
#define IDD_SEARCH                      121
#define IDD_SEARCHING                   122
#define IDD_GREPTAB_MAIN                123
#define IDD_GREPTAB_PERSIST             124
#define IDD_DIALOG1                     125
#define IDD_FILTERCTL                   126
#define IDD_DIALOG2                     127
#define IDD_PROPTAB_DEFNOTE             127
#define IDD_PROPTAB_SIP                 128
#define IDD_DETAILSVIEW                 129
#define IDB_MEMOSELECT_IMAGES24         131
#define IDD_BOOKMARK_EDIT               134
#define IDD_PROPTAB_EXTAPP              135
#define IDD_FILTERDEF_SRC               138
#define IDD_FILTERDEF_FILTER            139
#define IDD_FILTERDEF_ADD_REGEX         140
#define IDD_FILTERDEF_ADD_LIMIT         141
#define IDD_FILTERDEF_ADD_TIMESTAMP     142
#define IDD_FILTERDEF_ADD_SORT          143
#define IDD_LANG_DLG                    149
#define IDM_MAIN_MENUITEM1              401
#define IDM_MAIN_MENUITEM2              402
#define IDS_MAIN_MENUITEM1              410
#define IDS_MAIN_MENUITEM2              412
#define IDM_MAIN_MENU                   450
#define IDM_DETAILS_MENU                460
#define IDM_DETAILSDLG_MENU             461
#define IDC_PASS                        1001
#define IDC_TOPFOLDER                   1002
#define IDC_FOLDERSEL                   1003
#define IDC_FILESELECT_TREE             1004
#define IDC_PASS1                       1005
#define IDC_PASS2                       1006
#define IDC_PROP_PASSWORD_DESC          1007
#define IDC_NEWFOLDER_NAME              1008
#define IDC_PASS_TIMEOUT                1010
#define IDC_FONT_SELECT_NAME            1011
#define IDC_FONT_DETAILS_NAME           1012
#define IDC_FONT_SELECT_SIZE            1013
#define IDC_FONT_DETAILS_SIZE           1014
#define IDC_FONT_SELECT_USEDEFAULT      1015
#define IDC_FONT_DETAILS_USEDEFAULT     1016
#define IDC_PROP_DATEFORMAT1            1017
#define IDC_PROP_DATEFORMAT2            1018
#define IDC_PROP_SETPASS                1019
#define IDC_PROP_KEEPCARET              1020
#define IDC_PROP_APPBUTTON1             1021
#define IDC_PROP_APPBUTTON4             1022
#define IDC_PROP_TABSTOP                1022
#define IDC_PROP_APPBUTTON2             1023
#define IDC_PROP_SWITCHTITLE            1023
#define IDC_PROP_APPBUTTON3             1024
#define IDC_KEEPTITLE                   1024
#define IDC_PROP_APPBUTTON5             1025
#define IDC_PROP_EXTAPP_PATH_EXTAPP1    1025
#define IDC_SEARCH_CASESENSITIVE        1026
#define IDC_PROP_EXTAPP_PATH_EXTAPP2    1026
#define IDC_SEARCH_STRING               1027
#define IDC_SEARCH_ENCRYPTMEMO          1028
#define IDC_COPYRIGHT                   1029
#define IDC_FILENAMEONLY                1030
#define IDC_DATEFORMAT_DESC             1032
#define IDC_VERSIONINFO                 1033
#define IDC_SEARCH_DIRECTION_UP         1034
#define IDC_SEARCH_DIRECTION_DOWN       1035
#define IDC_SEARCHMSG                   1036
#define IDC_PROPTAB_DISABLEACTION       1037
#define IDC_GREPTAB_MAIN_SEARCHSTRING   1038
#define IDC_GREPTAB_MAIN_CASESENSITIVE  1039
#define IDC_BMEDIT_LIST                 1039
#define IDC_GREPTAB_MAIN_ENCRYPTNOTE    1040
#define IDC_BMEDIT_UP                   1040
#define IDC_GREPTAB_MAIN_FILENAME       1041
#define IDC_FILTERCTL_LIST              1041
#define IDC_BMEDIT_DOWN                 1041
#define IDC_GREPTAB_MAIN_STARTDIR       1042
#define IDC_FILTERCTL_KEEP              1042
#define IDC_BMEDIT_DELETE               1042
#define IDC_PROP_READONLY               1043
#define IDC_FILTERCTL_UP                1043
#define IDC_FILTERDEF_SRC_PATH          1043
#define IDC_FILTERCTL_DOWN              1044
#define IDC_FILTERDEF_FILTER_LIST       1044
#define IDC_PROP_SIPDELTA               1044
#define IDC_FILTERCTL_NEW               1045
#define IDC_FILTERDEF_FILTER_UP         1045
#define IDC_PROPTAB_FOLDER_LABEL        1045
#define IDC_FILTERDEF_FILTER_DOWN       1046
#define IDC_FILTERCTL_DELETE            1046
#define IDC_PROPTAB_DEFNOTE_PATH        1046
#define IDC_PROPTAB_FOLDER_HELP1        1046
#define IDC_FILTERDEF_FILTER_REGEX      1047
#define IDC_FILTERCTL_RENAME            1047
#define IDC_PROPTAB_DEFNOTE_SETCURRENT  1047
#define IDC_PROPTAB_FOLDER_HELP2        1047
#define IDC_FILTERDEF_REGEX_SEARCHSTR   1048
#define IDC_FILTERDEF_FILTER_LIMIT      1048
#define IDC_PROPTAB_DEFNOTE_SETBLANK    1048
#define IDC_FILTERDEF_REGEX_CASESENSITIVE 1049
#define IDC_FILTERDEF_FILTER_TIMESTAMP  1049
#define IDC_FILTERDEF_REGEX_CRYPTMEMO   1050
#define IDC_FILTERDEF_FILTER_SORT       1050
#define IDC_FILTERDEF_REGEX_FILENAME    1051
#define IDC_FILTERDEF_FILTER_DELETE     1051
#define IDC_FILTERDEF_REGEX_NEGATE      1052
#define IDC_FILTERDEF_ADD_REGEX_LABEL   1053
#define IDC_FILTERDEF_LIMIT_NUMLIMIT    1054
#define IDC_FILTERDEF_TS_DELTADAY       1055
#define IDC_FILTERDEF_ADD_LIMIT_ITEMS   1055
#define IDC_FILTERDEF_TS_OLDER          1056
#define IDC_FILTERDEF_TS_NEWER          1057
#define IDC_FILTERDEF_SORT_TYPE         1058
#define IDC_FILTERDEF_ADD_TIMESTAMP_BASEPOINT 1058
#define IDC_FONT_SELECT_CLEARTYPE       1059
#define IDC_FILTERDEF_ADD_SORT_LABEL    1059
#define IDC_FONT_DETAILS_CLEARTYPE      1060
#define IDC_GREPTAB_MAIN_POSLABEL       1060
#define IDC_GREPTAB_MAIN_STRLABEL       1061
#define IDC_PROPTAB_PASS_TIMEOUT_LABEL  1062
#define IDC_PROPTAB_PASS_TIMEOUT_HELP   1063
#define IDC_PROPTAB_FONT_TREE_LABEL     1064
#define IDC_PROP_EXTAPP_USEASSOC        1064
#define IDC_PROPTAB_FONT_EDIT_LABEL     1065
#define IDC_PROP_EXTAPP_TTL_EXTAPP1     1065
#define IDC_PROPTAB_INSDATE_DATE1       1066
#define IDC_PROP_EXTAPP_TTL_EXTAPP2     1066
#define IDC_PROPTAB_INSDATE_DATE2       1067
#define IDC_PROPTAB_EXTAPP_CHOOSE1      1067
#define IDC_PROPTAB_KEEPCARET_HELP1     1068
#define IDC_PROPTAB_EXTAPP_CHOOSE2      1068
#define IDC_PROPTAB_KEEPCARET_HELP2     1069
#define IDC_PROP_EXTAPP_CAUTION         1069
#define IDC_PROPTAB_KEEPCARET_HELP3     1070
#define IDC_PROPTAB_KEEPCARET_LABEL     1071
#define IDC_PROPTAB_DEFNOTE_LABEL       1072
#define IDC_SEARCH_FIND_LABEL           1073
#define IDC_SEARCH_DIRECT_LABEL         1074
#define IDC_PROPTAB_APPBTN_HELP         1075
#define IDC_PROPTAB_DISABLESAVEDLG      1076
#define IDC_PASS_TIMEOUT_USE_SAFEFILE   1077
#define IDC_PROPTAB_PASS_TIMEOUT_SAFEFILE_HELP 1078
#define IDC_LANG_LIST                   1099
#define IDM_ACTIONBUTTON                30001
#define IDM_FILE_EXIT                   40002
#define IDM_HELP_ABOUT                  40003
#define IDM_EXIT                        40003
#define IDS_MENUITEM40005               40006
#define IDM_EDIT_MEMO                   40007
#define IDM_DETAILSVIEW_CUT             40008
#define IDM_DETAILSVIEW_COPY            40009
#define IDM_DETAILSVIEW_PASTE           40010
#define IDS_MENUITEM40011               40012
#define IDM_MENUITEM3                   40013
#define IDS_MENUITEM40014               40015
#define IDS_MENUITEM40017               40018
#define IDM_NEWMEMO                     40019
#define IDS_MENUITEM40020               40021
#define IDM_RETURNLIST                  40022
#define IDM_ABOUT                       40023
#define IDM_ENCRYPT                     40024
#define IDM_DECRYPT                     40025
#define IDS_MENUITEM40027               40028
#define IDM_MENU_ENCRYPT                40029
#define IDS_PROPTAB_FOLDER              40029
#define IDM_DELETEITEM                  40030
#define IDS_PROPTAB_TITLE               40030
#define IDM_PROPERTY                    40031
#define IDS_PROPTAB_PASSWORD            40031
#define IDS_PROPERTY_PASSWORD_DESC      40032
#define IDM_NEW                         40032
#define IDS_MENUITEM40033               40034
#define IDM_NEWFOLDER                   40035
#define IDS_PROPTAB_PASS_TIMEOUT        40035
#define IDM_FORGETPASS                  40036
#define IDS_MENUITEM40037               40038
#define IDS_MENUITEM40039               40040
#define IDM_COPY                        40041
#define IDS_MENUITEM40041               40041
#define IDM_PASTE                       40042
#define IDS_PROPTAB_FONT                40042
#define IDM_CUT                         40043
#define IDM_SAVE                        40044
#define IDS_MENUITEM40045               40046
#define IDM_POPUP                       40047
#define IDS_MENUITEM40048               40049
#define ID_MENUITEM40050                40050
#define IDS_MENUITEM40051               40052
#define IDM_INSDATE                     40053
#define IDM_INSDATE1                    40053
#define IDS_PROPTAB_DATE                40053
#define IDM_INSDATE2                    40054
#define ID_MENUITEM40055                40055
#define IDS_MENUITEM40056               40057
#define IDS_PROPTAB_KEEPCARET           40058
#define IDM_SELALL                      40058
#define IDS_PROPTAB_APPBUTTON           40059
#define IDM_DETAILS_HSCROLL             40059
#define IDM_DETAILS_TOOL                40060
#define IDS_GREPTAB_MAIN                40060
#define IDS_GREPTAB_PERSIST             40061
#define IDM_SEARCH                      40062
#define IDS_PROPTAB_SIP                 40062
#define IDM_SEARCH_NEXT                 40063
#define IDS_PROPTAB_DEFNOTE             40063
#define IDM_SEARCH_PREV                 40064
#define IDM_RENAME                      40065
#define IDM_UNDO                        40067
#define IDM_TOGGLEREADONLY              40068
#define IDM_GREP                        40069
#define IDM_VFOLDER_DEF                 40070
#define IDS_MENUITEM40072               40073
#define IDM_BOOKMARK_ADD                40074
#define IDM_BOOKMARK_CONFIG             40075
#define IDM_MS_BOOKMARK                 40077
#define IDM_TOGGLEPANE                  40078
#define IDS_MENUITEM40079               40080
#define IDS_MENUITEM40081               40082
#define IDS_MENUITEM40083               40084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40085
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
